config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :users
  resources :reservations
  resources :books

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reservations
  belongs_to :author
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :book
  belongs_to :users

  def overdue?
    Date.today > return_date
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reservations
  has_many :books, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    redirect_to action: "show", id: @author.id
  end

  def create
    @author = Author.create(author)
    redirect_to action: "show", id: @author.id
  end

  def destroy
    @author = Author.find(params[:id]).destroy
    redirect_to action: "index"
  end


  private

  def author_params
    params.require(:author).permit(:name, :bio)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create book_params
    redirect_to action: "show", id: @book.id
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to action: "show", id: @book.id
  end

  def destroy
    @book = Book.find(params[:id]).destroy
    redirect_to action: "index"
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :author_id)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new({book_id: params[:book_id]})

  end

  def create
    @reservation = Reservation.create reservation_params
    redirect_to action: "show", id: @reservation
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  private

  def reservation_params
    params.require(:reservation).permit(:name, :return_date, :book_id)

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id]).destroy
    redirect_to action: "index"
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to action: "show", id: @user.id
  end

  def create
    @user = User.create(user_params)
    redirect_to action: "show", id: @user.id
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>
<p>Find me in app/views/authors/edit.html.erb</p>

app/views/authors/index.html.erb
<h1>Authors</h1>
<% @authors.each do |author|%>
<%= @author %>
<% end %>

app/views/authors/new.html.erb
<h1>Authors#new</h1>
<p>Find me in app/views/authors/new.html.erb</p>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Your Book</h1>
<%= form_for @book do |f|%>
<%= f.label :title %>
<%= f.text_field :title%>
<br>
<%= f.label :description %>
<%= f.text_field :description %> <br>
<br>

<p> <a href="/books">Home</a> </p>
<% end %>

app/views/books/index.html.erb
<h1>Library Books</h1>
<p>Here's all the books:</p>
  <p> <% @books.each do |book| %> </p>
  <ul>
    <%= link_to book.title, book %>    :
    <%= link_to "Reserve", new_reservation_path(book_id: book.id)%>
    <%= link_to "Delete", book_path(book.id), method: :delete %>
  </ul>
 <% end %>

 <p> <a href="/books/new">Add a new book</a> |
    <%= link_to "Current reservations", reservations_path %>
 </p>

app/views/books/new.html.erb
<h1>Add a new book</h1>
<p>Create your new book here:</p>

  <%= form_for @book do |f|%>
  <%= f.label :title %>:
  <%= f.text_field :title%> <br>

  <%= f.label :description %>:
  <%= f.text_field :description %>
  <br>
  Author: <%= select("book", "author_id", Author.all.collect {|a| [ a.name, a.id] }, {include_blank: "None"}) %>
  <br>
  <p> <%= f.submit %> </p>
  <% end %>



  <p> <a href="/books">Home</a> </p>

app/views/books/show.html.erb
<h1> Book Title: <%= @book.title %></h1>
<p>
  Description: <%= @book.description %>
<br>
  Author: <%= @book.author.name %>
</p>

  <p><%= link_to "Edit", edit_book_path %></p>
<p> <a href="/books">Home</a> </p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaceOfBooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations</h1>
<p>All reservations:</p>

<% @reservations.each do |reservation| %>
<%= reservation.book.title if reservation.book %> |
<% if reservation.overdue? %>
<span>Overdue!</span> |
<% end %>
Checked out to: <%= reservation.name %> |
Due Date: <%= reservation.return_date %> <br>
<% end %>




<p> <a href="/books">Home</a> </p>

app/views/reservations/new.html.erb
<p>
  <%= form_for @reservation do |f|%>
  <%= f.label :name %>
  <%= f.hidden_field :book_id %>
  <%= f.text_field :name%> <br>

  <%= f.label :return_date %>
  <%= f.date_field :return_date %> <br>
  <br>
  <%= f.submit %>
  <% end %>
</p>

app/views/reservations/show.html.erb
<h1>Confirm Reservation</h1>
<p>Reserved By: <%= @reservation.name %></p>
<p> Return Date: <%= @reservation.return_date %></p>
<%= link_to "Confirm", reservations_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>